name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: humble
