name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cpu:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: |
          apt update && rosdep update
          rosdep install -yi --from-paths .

      - name: Build workspace
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

  gpu_cuda:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: |
          apt update && rosdep update
          rosdep install -yi --from-paths .

      - name: Build workspace
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --cmake-args -DWITH_CUDA=ON
